service:
  name: ignite-serverless-challenge

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    
functions:
  hello:
    handler: src/handlers/hello.handle
    events:
      - http:
          path: /hello
          method: post
          cors: true  